### PR TITLE
Development

### PR DESCRIPTION
**Pull request by DanielMitiku**

### CODE REVIEW

**Review by inhaq — CHANGES_REQUESTED** [review]
### Good work guys 📈
Amazing to see these improvements so quick over your last projects. Remember, the more you practice, the easier it'll become. Here are some improvement, I want you to make:
 - Check your project for error [here](https://validator.w3.org), try to tweak all of them.
 - Try not to use `id` in CSS, unless required.
 - Clear floats, where floats are applied.
 - Update ReadMe file for this project

Kindly resubmit, once everything is done. Good luck 😊

**Comment by DanielMitiku** [comment]
Hey Inhaq, can you at the changes we made.

**Review by inhaq — CHANGES_REQUESTED** [review]
### Need some more work guys 🏋️‍♀️
[Here](https://snag.gy/V4NMIB.jpg) is few errors, need to be fixed. [This](https://snag.gy/YrHRza.jpg) part on right side is behind other div, due to it's width. Just need these to take care of, then you're good to go.
Once fixed, kindly resubmit for review. Happy coding 😊

**Comment by DanielMitiku** [comment]
We fixed the first part. But we made the other part like that because the website looks like that. The div is hidden in the website.

**Comment by DanielMitiku** [comment]
Made the width visible

**Review by inhaq — CHANGES_REQUESTED** [review]
Good job with `width`, [here](https://snag.gy/t8S2xB.jpg) is what you need to be fixed next. You just need to clear the floats and you're good to go.

**Review by inhaq — APPROVED** [review]
### That's 👍🏻 
Good luck with the next project. Kindly submit project completion form. Happy coding 😊

**Pull request merged**
